Capstone_task/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from band import views as band_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('band/', include('band.urls', namespace = 'band')),
    path('welcome/', band_views.welcome, name='welcome'),
    path('users/', include('users.urls', namespace = 'user')),
    path('register/', user_views.register, name='register'),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]
"""
URL configuration for the Django project.

Defines URL patterns for all the functions and views created in this Django project.

URL Patterns:
    - /admin/: URL pattern for the Django admin.
    - /band/: URL pattern for URLs defined in the 'band' app.
    - /welcome/: URL pattern for the welcome page.
    - /users/: URL pattern for URLs created in the 'users' app.
    - /register/: URL pattern for the user registration page.
    - /: URL pattern for the login page and uses Django's built-in LoginView.
    - /logout/: URL pattern for the logout page and uses Django's built-in LogoutView.

Each URL pattern is assigned to the appropriate view.
"""

band/urls.py
from django.urls import path
from . import views

app_name = 'band'
urlpatterns = [
    path('welcome/', views.welcome, name='welcome'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('songs/', views.song_list, name='song_list'),
    ]
"""
URL configuration for the band app.

Defines URL patterns for various pages of the band app, including the welcome page, about page, contact page, and song list page.

Attributes:
    app_name (str): The namespace for the band app URLs.

URL Patterns:
    - /welcome/: URL pattern for the welcome page.
    - /about/: URL pattern for the about page.
    - /contact/: URL pattern for the contact page.
    - /songs/: URL pattern for the song list page.

Each URL pattern is assigned to its corresponding view function.

"""

users/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
]
"""
URL configuration for the login app.

Defines URL patterns for the login app, including the home page and registration page.

Attributes:
    app_name (str): The namespace for the login app URLs.

URL Patterns:
    - /home/: URL pattern for the home page.
    - /register/: URL pattern for the registration page.

Each URL pattern is has been assigned to its corresponding view function.
"""

band/models.py
from django.db import models

# Create your models here.
    
class Song(models.Model):
    """
    A model representing a song object.

    Attributes:
        title (str): The name of the song.
        duration (timedelta): The duration of the song formated in HH:MM:SS.
        release_date (date): The release date of the song.

    Methods:
        __str__: Returns the title of the song as a string representation.
    
    """
    title = models.CharField(max_length=100)
    duration = models.DurationField() 
    release_date = models.DateField()

    def __str__(self):
        """
        Returns a string representation of the song.

        Returns:
            str: The title of the song.
        
        """
        return self.title

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
"""
Form for user registration.

Extends the built-in UserCreationForm provided by Django to include additional fields:
- first_name: First name of the user.
- last_name: Last name of the user.
- email: Email address of the user.

Inherits from:
    UserCreationForm: A form for creating a new user account.

Attributes:
    first_name (CharField): Field for entering the first name.
    last_name (CharField): Field for entering the last name.
    email (EmailField): Field for entering the email address.

Meta:
    model (User): The User model to use for registration.
    fields (list): List of fields to include in the form, including built-in and custom fields.
"""

band/views.py
"""
This module contains view functions for rendering various pages of the website.

The views include:
- Welcome page
- About Us page
- Contact details page
- List of songs
"""

from django.shortcuts import render
from .models import Song

# Create your views here.

def welcome(request):
    """
    Render the welcome page.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The welcome page.
    """
    return render(request, 'welcome.html')

def about(request):
    """
    Render the About Us page.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The About Us page.
    """
    return render(request, 'About_us.html')

def contact(request):
    """
    Render the contact details page.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The contact details page.
    """
    return render(request, 'contact_details.html')

def song_list(request):
    """
    Render a list of all songs.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The page with a list of songs.
    """
    songs = Song.objects.all()
    return render(request, 'About_us.html', {'songs': songs})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .forms import UserRegistrationForm

def home(request):
    """
    Render the home page.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: Renders home page called home.html.
    """
    return render(request, 'home.html')

def register(request):
    """
    This function handles user registration.

    If the request method is POST, the program attempts to process the registration form.
    If the form is valid, the program saves the user and redirects them to the login page.
    If the form is not valid, the program renders the registration form.
    If the request method is not POST, the program renders the registration form.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The registration page or the user is redirected to the login page.
    """
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been created. You can log in now!')    
            return redirect('login')
    else:
        form = UserRegistrationForm()

    context = {'form': form}
    return render(request, 'register.html', context)

band/templates/About_us.html
{% extends 'navbar.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>About us</title>
        <style>
            /* Body style */
            .body {
                color: black;
                text-align: center;
                justify-content: center; /* Center content horizontally */
                font-family: Arial, Helvetica, sans-serif;
            }
        </style>
    </head>
    <body>
        <h1><b>About us!</b></h1>
        
        <p class="body">We are an up-and-coming band based in South Africa! We have performed all around South Africa, and our songs have hit number 1 on the charts more than once. We have become an overnight sensation, and now it's time to level up our game. We will now be touring internationally, so please be sure to <a href="{% url 'login:register' %}"><b>sign up</b></a> for our newsletter to see when we will be touring in your area!</p>

        <!--Adding in the song list created from the admin page.-->
        <div class="container">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <h2><b>Some songs we've made!</b></h2>
                    {% include 'songs.html' %}
                </div>
            </div>
        </div>
    </body>
</html>
{% endblock content %}

band/templates/contact_details.html
{% extends 'navbar.html' %}
<!DOCTYPE html>
<html lang = "en">
    
    <head>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

        <title>Contact us</title>

        <style>
            /* Body style */
            .body{
            color:black;
            text-align: center justify;
            font-family: Arial, Helvetica, sans-serif;
            }
        </style>
    </head>
    <body>
        {% block content %}
        <h1><b>Contact us!</b></h1>
        
        <p class = "body">We enjoy performing for everyone! If you want us to perform at your venue
            please conact us via: 
        </p>
        <ul>
            <li>Manager number: 123456789</li>
            <li>Email: band@band.com</li>
        </ul>
        {% endblock content %}
    </body>
</html>

band/templates/navbar.html
<!DOCTYPE html>
<html lang="en">


    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>Nav bar</title>

    </head>
    <body>
        
        <!--Navagation bar from reference https://stackoverflow.com/questions/71242630/how-to-add-a-simple-navbar-to-all-my-pages-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">New Band</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class ="nav-time">
                            <a class="nav-link" href="{% url 'band:welcome' %}">Welcome</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:register' %}">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'band:contact' %}">Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'band:about' %}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock content %}
    </body>
</html>

band/templates/songs.html
{% block songs %}
    {% if songs %}
        <ul>
            {% for song in songs %}
                <li>{{ song.title }} - {{ song.duration }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No songs available.</p>
    {% endif %}
{% endblock songs %}

band/templates/welcome.html
{% extends 'navbar.html' %}

<!DOCTYPE html>
<html lang="en">

    {% load static %}

    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>New Band</title>

        <style>
            /* Image style setting to ensure it is centered */
            .custom-img {
                display: block;
                margin: auto; /* Center the image horizontally */
                width: 100%; /* Adjust the width as needed */
                max-width: 300px; /* Ensure the image doesn't exceed its container */
                height: 200px;
                border: 5px solid;
            }

            /* Body style */
            .body {
                color: black;
                text-align: center;
                font-family: Arial, Helvetica, sans-serif;
            }
        </style>
    </head>

    <body>
        {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <h1 class="mb-4"><b>Welcome to our info Site!</b></h1>
                    <img class="custom-img" src="{% static 'assets/band_picture.jpg' %}" alt="Band photo">
                </div>
            </div>
        </div>

            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <p class="body"> Please <a href="{% url 'user:register' %}">sign up</a> to get the latest info about our
                        group and get the latest info relating to our shows!</p>
                    <p class='body'> Please feel free to make a <a href="{% url 'band:contact' %}">booking!</a></p>
                    <p class='body'> If you want to learn more about the band please click <a href="{% url 'band:about' %}">here!</a>
                    </p>
                </div>
            </div>
        {% endblock content %}
    </body>
</html>

users/templates/home.html
{% if user.is_authenticated %}
    <div class="alert alert-success" role="alert">
        <h3>Welcome {{ user.username }}!</h3>
        <a href="{% url 'logout' %}">Logout?</a>
    </div>
{% else %}
    <div class="alert alert-success" role="alert">
        <h3>Welcome!</h3>
        <a href="{% url 'register' %}">Signup</a>
        <a href="{% url 'login' %}">Login</a>
    </div>
{% endif %}

users/templates/login.html
<h3>login</h3>

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
        <p>{{ field.label }}: <br> {{ field }}</p>
    {% endfor %}
    <button type="submit">Login</button>
</form>

<p>Don't have an account? <a href="{% url 'register' %}">Signup here</a></p>

users/templates/logout.html
{% extends 'band/welcome.html' %}

{% block content %}
    <br>
    <div class="alert alert-success" role="alert">
        <h2 style="text-align: center;">Logged out!</h2>
    </div>

    <h3>Login again?</h3>
    <a href="{% url 'login' %}">---> Login</a> <br>
    <a href="{% url 'band:band' %}"><--- Or go back to home.</a>
{% endblock content %}

users/templates/register.html
<h3>Register here</h3>
<hr>

<form action="" method="POST">
    {% csrf_token %}

    {% for field in form %}
        <div>
            <p>{{ field.label }}: <br> {{ field }}</p> 

            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </div>
    {% endfor %}
    <button type="submit">Register</button>
</form>